language: ruby
rvm:
- 2.0.0
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- bundle rake db:schema:load
- bundle exec cucumber
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: J2wFc6RtyBezTJsHudkubop0W/qXA1/0aehVX0eHohrU2zZbmU+CCH+zOxs5CrB9843AWz1qaY0YFnDw7TkQQat4Hmnez0HQcWHJWuD1vd8KnofS7Nmy/B7CC6wf9ewTjNmLEI7sydrt77FUjaO1PwhVeYsVKBz9kQ011I8n4sU=
  app: orphan-commit
  on:
    repo: nygrenh/orphan_commit
  run: "rake db:migrate"
